name: ndviewer_light
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - tifffile
  - dask
  - xarray
  - superqt
  - pyqt
  - vispy
  - ndv
  - pip
  - pip:
    - tensorstore
